config/routes.rb
Rails.application.routes.draw do
  get 'worker_bees/index'

  root to: 'worker_bees#index'
  resources :worker_bees, only: [:index, :show, :update]
  resources :appointments, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# == Schema Information
#
# Table name: appointments
#
#  id            :bigint           not null, primary key
#  worker_bee_id :bigint           not null
#  date          :date             not null
#  pollen_globs  :decimal(3, 1)
#  nectar        :integer          not null
#  advisement    :integer
#  adv_accepted  :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Appointment < ApplicationRecord
  belongs_to :worker_bee

  validates :worker_bee,  presence: { message: "must be linked" }
  validates :date,        presence: true
  validates :pollen_globs,
    numericality: { greater_than_or_equal_to: 5, less_than_or_equal_to: 17.9,
      allow_nil: true }
  validates :nectar,      presence: true,
    numericality: { only_integer: true }
  validates :advisement,
    numericality: { only_integer: true, greater_than_or_equal_to: 200,
      less_than_or_equal_to: 20000, allow_nil: true }
  validate :nectar_val,   :advisement_increment

  private
    def nectar_val
      if nectar == 0 || nectar == nil
        return
      elsif nectar < 200 || nectar > 20000
        errors.add(:nectar, "must either be 0 or be between 200 and 20,000")
      elsif nectar % 100 != 0
        errors.add(:nectar, "must be in 100 increments")
      end
    end
    
    def advisement_increment
      unless advisement == nil || advisement % 100 == 0
        errors.add(:advisement, "must be in 100 increments")
      end
    end
end

app/models/comb.rb
# == Schema Information
#
# Table name: combs
#
#  id         :bigint           not null, primary key
#  supervisor :string           not null
#  sweet_spot :decimal(3, 1)    not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comb < ApplicationRecord
  has_many :worker_bees, inverse_of: :comb
  
  validates :supervisor, presence: true
  validates :sweet_spot, presence: true,
    numericality: { greater_than_or_equal_to: 5.1, less_than_or_equal_to: 17.9 }
    # Usually between 10.0 and 15.0, but not always
end

app/models/worker_bee.rb
# == Schema Information
#
# Table name: worker_bees
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string           not null
#  comb_id    :bigint           not null
#

class WorkerBee < ApplicationRecord
  default_scope { order(id: :asc) }

  belongs_to :comb

  has_many :appointments, -> { order(date: :desc) }, inverse_of: :worker_bee,
    dependent: :destroy
  
  validates :name, presence: true
  validates :comb, presence: { message: "affiliation required" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def update
    appointment = Appointment.find(params[:id])

    if appointment.update(adv_accepted: false)
      redirect_to worker_bee_path(appointment.worker_bee_id)
    else
      render worker_bee_path(appointment.worker_bee_id), status: 422
    end
  end

  # Note: Decided that update just changes true/false (Accepted/Overruled)
  #       status, not past nectar or advisement amounts.

  # private
  #   def appointment_params
  #     params.require(:appointment).permit(:nectar, :advisement)
  #   end
end

app/controllers/concerns/calculate_percent_accepted.rb
module CalculatePercentAccepted
  extend ActiveSupport::Concern

  # def index
  #   Appointment.where().pluck(:nectar, :advisement)
  # end

  # private
  #   def worker_bee_params
  #   end
end

app/controllers/worker_bees_controller.rb
class WorkerBeesController < ApplicationController
  def index
    @worker_bees = WorkerBee.all.includes(:appointments)
    @hive_metrics = {
      num_combs: Comb.count,
      total_pg: Appointment.sum(:pollen_globs),
      total_nectar: Appointment.sum(:nectar)
    }
  end

  def show
    @worker_bee = WorkerBee.find(params[:id])
    @combs = Comb.all # need combs for comb reassignment select dropdown

    gon.push({
      appointments: @worker_bee.appointments
    })

    bee_ne = @worker_bee.appointments.sum(:nectar)
    bee_pg = @worker_bee.appointments.sum(:pollen_globs)
    bee_ne_pg = (bee_ne / bee_pg).round()

    hive_ne = Appointment.sum(:nectar)
    hive_pg = Appointment.sum(:pollen_globs)
    hive_ne_pg = (hive_ne / hive_pg).round()
    vs_hive = bee_ne_pg - hive_ne_pg
    vs_hive = "+#{vs_hive}" if vs_hive > 0

    comb_appts = Appointment.joins(:worker_bee).where("worker_bees.comb_id = ?", @worker_bee.comb_id)
    comb_ne = comb_appts.sum(:nectar)
    comb_pg = comb_appts.sum(:pollen_globs)
    comb_ne_pg = (comb_ne / comb_pg).round()
    vs_comb = bee_ne_pg - comb_ne_pg
    vs_comb = "+#{vs_comb}" if vs_comb > 0

    gon.push({
      vs_hive: vs_hive,
      vs_comb: vs_comb
    })

    @bee_metrics = {
      days_since_last: (DateTime.current.to_date - @worker_bee.appointments.first.date).to_s[0..-3],
      bee_pg: bee_pg,
      bee_ne: bee_ne,
      bee_ne_pg: bee_ne_pg,
      vs_hive: vs_hive,
      vs_comb: vs_comb
    }
  end

  def update
    @worker_bee = WorkerBee.find(params[:id])
    old_comb_id = @worker_bee.comb_id.to_s

    if @worker_bee.update(worker_bee_params)
      flash[:notice] = worker_bee_params[:comb_id] == old_comb_id ?
        "Already in this comb" : "Reassigned!"

      redirect_to @worker_bee
    else
      flash.now[:error] = "Could not assign to comb"
      render :show, status: 422
    end
  end

  private
    def worker_bee_params
      params.require(:worker_bee).permit(:comb_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_appointment.html.slim
/ --- Table Row --- /
tr id="appt-#{appointment.id}"
  td.collapse-col = @worker_bee.id
  td.collapse-col = "#{@worker_bee.id}-C#{@worker_bee.comb_id}"
  td = appointment.date
  td = appointment.pollen_globs ? "#{appointment.pollen_globs} p/g" : "n/a"
  td = "#{appointment.nectar} units"
  td = appointment.advisement ? "#{appointment.advisement} units" : "n/a"
  td.percent-accepted.collapse-col
  td.overrule-col
    - if appointment.adv_accepted

      = form_with model: appointment, html: { class: "edit-form hide" } do |f|
        = f.hidden_field :id
        = f.submit "Overrule", { class: "orange" }

      button.edit-toggle-button onclick="toggleEdit('appt', #{appointment.id})"
        | Edit Advisement

    - elsif appointment.adv_accepted == false
      span Overruled

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Honey by Jaehyuk Lee</title>
    <%= csrf_meta_tags %>
    <%= Gon::Base.render_data %>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="app">
      <div id="page-wrapper">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/worker_bees/_form.html.slim
.comb-info
  .comb-id
    = @worker_bee.comb_id

  = form_with model: @worker_bee, html: { class: "edit-form hide" } do |f|
    = f.select :comb_id, options_from_collection_for_select(@combs, :id, :id, "#{@worker_bee.comb_id}")
    = f.submit "Submit", { class: "blue" }

  button.edit-toggle-button onclick="toggleEdit('bee', #{@worker_bee.id})"
    | Change comb

.form-notice
  - if flash[:notice]
    = flash[:notice]
  - if flash[:error]
    = flash[:error]

app/views/worker_bees/index.html.slim
/ --- Header --- /
section.header
  .header-left
    = fa_icon "home"

  .page-title Worker Bees Index

  .header-right
    = fa_icon "forumbee"

#main
  / --- Hive Overview Card --- /
  section.hive-info
    h2 Hive Overview

    table
      tbody
        tr
          td Worker Bee Population: 
          td = @worker_bees.count
        tr
          td Number of Combs: 
          td = @hive_metrics[:num_combs]
        tr
          td Total PollenGlobs Collected: 
          td = "#{@hive_metrics[:total_pg]} p/g"
        tr
          td Total Nectar Consumption: 
          td = "#{(@hive_metrics[:total_nectar] / 1000000.0).round(2)} million units"
        tr
          td Avg Nectar Cost per PollenGlob
          td = "#{(@hive_metrics[:total_nectar] / @hive_metrics[:total_pg]).round()} units per p/g"


  / --- Bees Index --- /
  section.bees-table-container
    table
      thead
        tr
          th ID-CombID
          th Name
          th Last Reported
          th 

      - @worker_bees.each do |bee|
        tr
          td = "#{bee.id}-C#{bee.comb_id}"
          td = "#{bee.name}"
          td = "#{bee.appointments.first.date}"
          td = link_to  "See Details", worker_bee_path(bee)

app/views/worker_bees/show.html.slim
/ --- Header --- /
section.header
  .header-left
    = fa_icon "home"
    = link_to  "Back to Index", worker_bees_path, { class: "orange" }

  .page-title Worker Bee Details

  .header-right
    = fa_icon "forumbee"


/ --- ID Card --- /
section.id-card id="bee-#{@worker_bee.id}"
  table
    tbody
      tr
        td Name: 
        td = @worker_bee.name
      tr
        td Days Since Last Report: 
        td = "#{@bee_metrics[:days_since_last]} day(s)"
      tr
        td PollenGlobs Collected: 
        td = "#{@bee_metrics[:bee_pg]} p/g"
      tr
        td Nectar Consumed: 
        td = "#{@bee_metrics[:bee_ne]} units"
      tr
        td Efficiency Metric: 
        td = "#{@bee_metrics[:bee_ne_pg]} units per p/g"
      tr
        td vs Hive Avg: 
        td.vs-hive = "#{@bee_metrics[:vs_hive]} units per p/g"
      tr
        td vs Comb Avg: 
        td.vs-comb = "#{@bee_metrics[:vs_comb]} units per p/g"
      tr.comb-edit-row
        td Comb Affiliation: 
        td = render "worker_bees/form"
      tr
        td Comb's Sweet Spot: 
        td = "#{@worker_bee.comb.sweet_spot} p/g"
      tr
        td Comb Supervisor: 
        td = @worker_bee.comb.supervisor


/ --- Graph --- /
section.graph
  figure.highcharts-figure
    #graph-container


/ --- Table --- /
section.table
  button.table-toggle-button onclick="toggleTable()"
    | View in Enhanced Mode

  table
    thead
      tr
        th.collapse-col ID
        th.collapse-col ID-CombID
        th Date
        th PollenGlobs
        th Nectar
        th Advisement
        th.collapse-col % Accepted
        th.overrule-col Overrule
    = render @worker_bee.appointments


/ --- Script on Page Load --- /
javascript:
  onShowPageLoad();